pipelines:
  unzip:
    label: "Hier entpacken"
    icon: "folder-zip"
    source_types:
      - "application/zip"
      - "application/x-zip-compressed"
      - "application/java-archive"
    shares:
      type: "parentDir"
    job:
      type: "unzip"
      timeout: 300s
    target:
      extension: ""
      location: "same"
    notification: "toast"

  zip-create:
    label: "Als ZIP komprimieren"
    icon: "file-zip"
    source_types:
      - "*"
    shares:
      type: "parentDir"
    job:
      type: "zip-create"
      timeout: 300s
    target:
      extension: ".zip"
      location: "same"
    notification: "toast"

  tar-extract:
    label: "Archiv entpacken"
    icon: "folder-zip"
    source_types:
      - "application/x-tar"
      - "application/gzip"
      - "application/x-bzip2"
      - "application/x-xz"
    shares:
      type: "parentDir"
    job:
      type: "tar-extract"
      timeout: 300s
    target:
      extension: ""
      location: "same"
    notification: "toast"
