pipelines:
  build-kosmos:
    label: "Build OpenCloud"
    icon: "hammer"
    source_types: []
    menu: "back"
    target:
      extension: ""
      location: ""
    job:
      type: "build-kosmos"
      timeout: 1800s
      params:
        branch: "kosmos"
        push: true
        deploy: false
    notification: "toast"
