pipelines:
  build-web:
    label: Build Web UI
    icon: layout-grid
    source_types: []
    menu: back
    target:
      extension: ""
      location: ""
    job:
      type: build-web
      timeout: 1800s
      max_retries: 2
      params:
        branch: kosmos
        push: true
    notification: toast
