pipelines:
  doc-to-pdf:
    label: "Als PDF exportieren"
    icon: "file-pdf"
    source_types:
      - "application/msword"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
      - "application/vnd.ms-excel"
      - "application/vnd.ms-powerpoint"
      - "application/vnd.oasis.opendocument.text"
      - "application/vnd.oasis.opendocument.spreadsheet"
      - "application/vnd.oasis.opendocument.presentation"
      - "application/rtf"
    shares:
      type: "parentDir"
    job:
      type: "office-to-pdf"
      timeout: 120s
    target:
      extension: ".pdf"
      location: "same"
    notification: "toast"

  mmd-to-pdf:
    label: "Diagramm als PDF"
    icon: "file-pdf"
    source_types:
      - "text/vnd.mermaid"
      - "application/vnd.chipnuts.karaoke-mmd"
    shares:
      type: "parentDir"
    job:
      type: "mmd-to-pdf"
      timeout: 60s
    target:
      extension: ".pdf"
      location: "same"
    notification: "toast"

  md-to-pdf:
    label: "Markdown als PDF"
    icon: "file-pdf"
    source_types:
      - "text/markdown"
      - "text/x-markdown"
    shares:
      type: "parentDir"
    job:
      type: "md-to-pdf"
      timeout: 60s
    target:
      extension: ".pdf"
      location: "same"
    notification: "toast"
